services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: devio
      POSTGRES_PASSWORD: devio
      POSTGRES_DB: devio
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
