"""add auto gen uuid

Revision ID: 05b5beebb270
Revises: 819f45da0f25
Create Date: 2026-09-05 21:35:17.307149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b5beebb270'
down_revision: Union[str, Sequence[str], None] = '819f45da0f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'badges', 'id',
        existing_type=sa.Uuid(),
        server_default=sa.text('gen_random_uuid()'),
    )
    op.alter_column(
        'user_badges', 'id',
        existing_type=sa.Uuid(),
        server_default=sa.text('gen_random_uuid()'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_badges', 'id', existing_type=sa.Uuid(), server_default=None)
    op.alter_column('badges', 'id', existing_type=sa.Uuid(), server_default=None)
