"""add icon field for Roadmap

Revision ID: 1e8182c898e0
Revises: f801f9f98c50
Create Date: 2026-10-01 22:02:36.974141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8182c898e0'
down_revision: Union[str, Sequence[str], None] = 'f801f9f98c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('icon', sa.String(), nullable=False, server_default='icon'))
    # ### end Alembic commands ###
    op.alter_column('roadmaps', 'icon', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'icon')
    # ### end Alembic commands ###
