"""add description for stage

Revision ID: 1e87e2c172ec
Revises: ee9641600dc7
Create Date: 2026-08-18 19:50:32.505574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e87e2c172ec'
down_revision: Union[str, Sequence[str], None] = 'ee9641600dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'description')
    # ### end Alembic commands ###
