"""add badges

Revision ID: 237e8d2ee4bf
Revises: 99eb5c4e36b5
Create Date: 2026-09-25 12:20:44.374230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237e8d2ee4bf'
down_revision: Union[str, Sequence[str], None] = '99eb5c4e36b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('tier', sa.Enum('common', 'rare', 'epic', 'legend', name='badgetier'), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_badges_code'), 'badges', ['code'], unique=True)
    op.create_table('user_badges',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('badge_id', sa.Uuid(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.alter_column('roadmaps', 'status',
               existing_type=sa.VARCHAR(length=6),
               server_default=sa.text("'draft'"),
               existing_nullable=False)
    op.alter_column('stages', 'duration_weeks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stages', 'duration_weeks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('roadmaps', 'status',
               existing_type=sa.VARCHAR(length=6),
               server_default=sa.text("'DRAFT'::character varying"),
               existing_nullable=False)
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_badges_code'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
