"""fix roadmap status enum values to lowercase

Revision ID: 5bad1f46dcd6
Revises: b8470619b6a1
Create Date: 2026-08-19 20:20:50.349318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bad1f46dcd6'
down_revision: Union[str, Sequence[str], None] = 'b8470619b6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
