"""add topics, duration_weeks field

Revision ID: 8a894e3598af
Revises: 1e87e2c172ec
Create Date: 2026-08-19 15:00:01.584047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a894e3598af'
down_revision: Union[str, Sequence[str], None] = '1e87e2c172ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('stages', sa.Column('duration_weeks', sa.Integer(), nullable=False, server_default=sa.text("0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'duration_weeks')
    op.drop_column('stages', 'topics')
    # ### end Alembic commands ###
