"""add field username and display_name for user table

Revision ID: 99eb5c4e36b5
Revises: 5bad1f46dcd6
Create Date: 2026-08-28 23:34:20.778020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99eb5c4e36b5'
down_revision: Union[str, Sequence[str], None] = '5bad1f46dcd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
