"""unique user stage progress

Revision ID: b42b106e4bd7
Revises: d0412b4d2497
Create Date: 2026-08-02 23:45:53.879387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42b106e4bd7'
down_revision: Union[str, Sequence[str], None] = 'd0412b4d2497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_stage', 'stage_progress', ['user_id', 'stage_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_stage', 'stage_progress', type_='unique')
    # ### end Alembic commands ###
