"""addfield status for roadmap

Revision ID: b8470619b6a1
Revises: 8a894e3598af
Create Date: 2026-08-19 20:01:30.293381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8470619b6a1'
down_revision: Union[str, Sequence[str], None] = '8a894e3598af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', name='statusenum', native_enum=False), server_default=sa.text("'DRAFT'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'status')
    # ### end Alembic commands ###
