"""add new tier for badges (myth)

Revision ID: f801f9f98c50
Revises: 237e8d2ee4bf
Create Date: 2026-09-27 20:50:49.458405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f801f9f98c50'
down_revision: Union[str, Sequence[str], None] = '237e8d2ee4bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE badgetier ADD VALUE IF NOT EXISTS 'mythic'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
